GET http://localhost:8080/stores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFiMDRhZTU5LWEyY2MtNDljZS05NDUyLTU3ODhhN2YwMDVjMSIsInVzZXIiOiJCaW9jb29wIiwiaWF0IjoxNjA2OTI2MjY1LCJleHAiOjE2MDY5Mjk4NjV9.ZBm7ZTULf50gGYIzXRYZ0oUjBSQkdt5W4Njyu0GNhWI


###
POST http://localhost:8080/stores
Content-Type: application/json

{
    "name": "Juillan"
}

###
PUT http://localhost:8080/stores/608f657f-3d8a-42a0-8e04-a35c4e667618
Content-Type: application/json

{
    "name": "Juillan"
}

###
GET http://localhost:8080/stores/608f657f-3d8a-42a0-8e04-a35c4e667610