GET http://localhost:8080/wines HTTP/1.1

###

POST http://localhost:8080/wines
Content-Type: application/json

{
    "title": "Bordeaux1",
    "type": "rouge",
    "image": "https://www.bienmanger.com/tinyMceData/images/categories/1423/valeur-sure-kressmann.jpg",
    "temperature": "15.2",
    "region":"nouvelle-aquitaine",
    "description": "lorem ipsum",
    "list_dishes": ["viande rouge", "poulet"],
    "logo": ["https://www.bienmanger.com/tinyMceData/images/categories/1423/valeur-sure-kressmann.jpg","https://www.bienmanger.com/tinyMceData/images/categories/1423/valeur-sure-kressmann.jpg"],
    "price_indicator": "€-€€",
    "StoreUuid": ["26690200-4f04-49cc-831c-a4f5e9488f41"]
}


###

GET http://localhost:8080/wines/ba0b1119-249e-46a2-aa98-85decedcbfd

####

PUT http://localhost:8080/wines/76b4283e-b94a-401f-922d-b9fdd107e719
Content-Type: application/json

{
    "tit": "Bordeaux"
}

### 
DELETE http://localhost:8080/wines/e74428b6-f92d-41b0-8999-20c768c7cb78


