GET http://localhost:8080/wines HTTP/1.1

###

POST http://localhost:8080/wines
Content-Type: application/json

{
    "title": "Baba",
    "type": "rouge",
    "image": "https://www.bienmanger.com/tinyMceData/images/categories/1423/valeur-sure-kressmann.jpg",
    "temperature": "15.2",
    "region":"nouvelle-aquitaine",
    "description": "lorem ipsum",
    "list_dishes": ["viande rouge", "poulet"],
    "logo": ["https://www.bienmanger.com/tinyMceData/images/categories/1423/valeur-sure-kressmann.jpg","https://www.bienmanger.com/tinyMceData/images/categories/1423/valeur-sure-kressmann.jpg"],
    "price_indicator": "€-€€",
    "StoreUuid": "0a8fab9e-944a-4792-93ff-05bae3c089df"
}


###

GET http://localhost:8080/wines/5e0be493-e681-4776-bff7-29e18d790f11

####

PUT http://localhost:8080/wines/54a29a05-ee89-4b2a-b905-7e0437e1a4ea
Content-Type: application/json

{
    "tit": "Bordeaux"
}


